apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-first-deployment
  labels:
    app: my-first-deployment
spec:
  replicas: 5
  selector:
    matchLabels:
      app: my-first-deployment
  template:
    metadata:
      labels:
        app: my-first-deployment
    spec:
      volumes:
        - name: my-first-pd
          persistentVolumeClaim:
            claimName: my-first-pvc
      containers:
      - name: my-first-deployment
        image: nginx:latest
        volumeMounts:
        - mountPath: "/usr/share/nginx/html"
          name: my-first-pd
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-first-pvc
spec:
  storageClassName: my-first-sc
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---

apiVersion: v1
kind: Service
metadata:
  name: my-first-service
spec:
  selector:
    app: my-first-deployment
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  #type: ClusterIP

---

