apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: my-first-sc
  annotations:
provisioner: microk8s.io/hostpath
reclaimPolicy: Delete
allowVolumeExpansion: true
volumeBindingMode: WaitForFirstConsumer

---

apiVersion: v1
kind: PersistentVolume
metadata:
  name: my-first-pv
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: my-first-sc
  hostPath:
    path: "/home/student/may_training/hostpath"
