apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: pg-storage-class
provisioner: csi-driver.example-vendor.example
reclaimPolicy: Delete
allowVolumeExpansion: true
hostPath:
  path: "/home/student/may_training/postgres/storage"
volumeBindingMode: WaitForFirstConsumer

